name: Continuous Integration

on:
  pull_request:
    branches: [ master ]

jobs:
  test_firestore:
    name: 🔥 🧪 Run Firestore tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
        
      - run: cd functions
      - run: npm install
      - run: npm run build
        
      - run: npm install -g firebase-tools

      - run: cd test/firestore_test
      - run: npm install
      - run: cd ../..

      - run: firebase emulators:exec "cd test/firestore_test && npm test"