name: Continuous Integration

on:
  pull_request:
    branches: [ master ]

jobs:
  test_firestore:
    name: 🔥 🧪 Run Firestore tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: 🔥 Install Firebase CLI
        run: npm install -g firebase-tools
        
      - name: ☁ Install functions dependencies
        working-directory: ./functions
        run: |
          npm ci
          npm run build
        
      - name: ⬇ Install tests dependencies
        working-directory: ./test/firestore_test
        run: npm install

      - name: 🧪 Run tests
        run: firebase emulators:exec "cd test/firestore_test && npm test"
  
  test_all:
    name: 🔥 🧪 Run flutter tests
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2

      - name: 🔥 Install Firebase CLI
        run: npm install -g firebase-tools
        
      - name: ☁ Install functions dependencies
        working-directory: ./functions
        run: |
          npm ci
          npm run build
        
      - name: 🧪 Run Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          scrips: sh test.sh true