name: Continuous Integration

on:
  pull_request:
    branches: [ master ]

jobs:
  test_firestore:
    name: 🔥 🧪 Run Firestore tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: 🔥 Install Firebase CLI
        run: npm install -g firebase-tools
        
      - name: ⬇ Install tests dependencies
        working-directory: ./test/firestore_test
        run: npm install

      - name: 🧪 Run tests
        run: firebase emulators:exec --only firestore "cd test/firestore_test && npm test"